### ISSUE TITLE
toContainer() broken for DataSerializable with vanilla data

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/Sponge#1316]
@gabizou  toContainer() broke with the changes to custom data.

Example:
```java
ItemStack item = ItemStack.of(ItemTypes.STONE, 1);
item.offer(Keys.DISPLAY_NAME, Text.of("test"));
item.toContainer();
```
Stacktrace:
```
org.spongepowered.api.data.DataRegistrationNotFoundException: Could not locate a DataRegistration for class class org.spongepowered.common.data.manipulator.mutable.SpongeDisplayNameData
	at org.spongepowered.common.data.SpongeManipulatorRegistry.getRegistrationFor(SpongeManipulatorRegistry.java:149) ~[SpongeManipulatorRegistry.class:?]
	at org.spongepowered.common.data.util.DataUtil.getRegistrationFor(DataUtil.java:430) ~[DataUtil.class:?]
	at org.spongepowered.common.data.util.DataUtil.getSerializedManipulatorList(DataUtil.java:133) ~[DataUtil.class:?]
	at net.minecraft.item.ItemStack.toContainer(ItemStack.java:2518) ~[ItemStack.class:?]
...
```
Should these datamanipulators be included in the toContainer Result? e.g. DisplayName is already included under UnsafeData in the DataContainer.

**Comment by codeHusky** [comment]
I'll also note that this is also broken with TypeToken serialization with configuration nodes.

**Comment by gabizou** [comment]
This should be fixed with the latest commits from yesterday. Verify it's still an issue on the latest builds, if not close the issue.

**Comment by Faithcaio** [comment]
@gabizou ItemStack#toContainer seems to be working now but Entity#toContainer (and possibly others?) are not working yet.

e.g.:
```
player.getLocation().createEntity(EntityTypes.SHEEP).toContainer();
```
```
org.spongepowered.api.data.DataRegistrationNotFoundException: Could not locate a DataRegistration for class class org.spongepowered.common.data.manipulator.mutable.entity.SpongeGravityData
	at org.spongepowered.common.data.SpongeManipulatorRegistry.getRegistrationFor(SpongeManipulatorRegistry.java:149) ~[SpongeManipulatorRegistry.class:?]
	at org.spongepowered.common.data.util.DataUtil.getRegistrationFor(DataUtil.java:430) ~[DataUtil.class:?]
	at org.spongepowered.common.data.util.DataUtil.getSerializedManipulatorList(DataUtil.java:133) ~[DataUtil.class:?]
	at net.minecraft.entity.Entity.toContainer(Entity.java:6278) ~[Entity.class:?]
```

**Comment by codeHusky** [comment]
The related data translators (CONFIGURATION_NODE) seem to be broken as well since the furthest back version I tested (vanilla 217)

**Comment by gabizou** [comment]
> The related data translators (CONFIGURATION_NODE) seem to be broken as well since the furthest back version I tested (vanilla 217)

Separate issue, keep on topic.

> @gabizou ItemStack#toContainer seems to be working now but Entity#toContainer (and possibly others?) are not working yet.

Gotcha, I'll have a fix out sometime today.

**Comment by Faithcaio** [comment]
@gabizou 
Snapshots are affected too. (ItemStackSnapshot, BlockSnapshot, EntitySnapshot)

**Comment by Faithcaio** [comment]
probably all fixed in 3634fcb0

**Comment by Zerthick** [comment]
This is still occurring as of SpongeForge-1.11.2-2282-6.1.0-BETA-2352

**Comment by Zerthick** [comment]
@Faithcaio Any chance this could be cherry-picked back to the API6 stable branch? :smile:

**Comment by Faithcaio** [comment]
@Zerthick sure ; it is done

**Comment by Zerthick** [comment]
@Faithcaio Thank you! :+1:
