### ISSUE TITLE
Command Blocks stop working under 1.12.2 after teleporting

### ISSUE THREAD

**Issue by eheimer** [SpongePowered/Sponge#1718]
**I am currently running**
- SpongeForge version: 1.12.2-2555-7.1.0-BETA-2840, also tested with BETA-2758 with same problem
- Java version: 8
- Operating System: tested on both Ubuntu and Debian

- Plugins/Mods: NONE, only SpongeForge

**Issue Description**
After a player teleports to the nether, ops are no longer able to right-click on command blocks.  EDIT: it seems to be player dependent, where only the player that travels is the one that has the problem.  Our initial testing seemed to indicate that all ops were affected when any player travelled, but I have not been able to reproduce that.

**Steps to reproduce**
Start a clean server with forge-1.12.2-14.23.1.2555-universal.jar and no mods installed other than SpongeForge, and no plugins.  First place a command block in the overworld and observe that you can right-click on it to get the interface, then create a portal to the nether and go through it.  In the nether you can place another command block if you wish, but will not be able to right-click on it.  Regardless, when you travel back to the overworld, you will not be able to right-click on the original command block that you placed either.

**A workaround**
After observing the problem, if you issue the /op command on yourself, all will be well and you can once again interface with the command blocks.

**Further testing**
I saw somewhere an explanation that suggested this might be a client issue.  That the client tracks whether or not it is an "op", and somehow that flag gets lost when traveling to other worlds/dimensions.  This seems to make sense.  I did verify that my client is also running the 2555 forge version.  With that thought, I also tested a clean forge server without SpongeForge or any other mods, and I did not have the same problem.  So it seems there is some interaction with Sponge and Forge that is causing the problem.

**Comment by phit** [comment]
Technically a dupe of https://github.com/SpongePowered/SpongeForge/issues/1838
But gonna leave this open, check if it happens with SpongeVanilla too, and then close my issue probably.

**Comment by ryantheleach** [comment]
Reproducible on Sponge Vanilla 7.1.0-BETA-10

**Comment by LXGaming** [comment]
Still an issue on the following:
 - SpongeVanilla: 1.12.2-7.1.0-BETA-38
 - SpongeForge: 1.12.2-2611-7.1.0-BETA-3005 (Forge: 1.12.2-14.23.2.2645 & 1.12.2-14.23.2.2611)

No Plugins/Mods were installed during testing.

**Comment by Aaron1011** [comment]
Fixed in the latest `stable-7`.

**Comment by kencinder** [comment]
This is still an issue on 3160 for me.
Have `minecraft` for permission node as Admin, log on and switch to Creative mode, command block access is fine.
Teleport to another world, come back and it no longer works. Have to use /op to access command blocks.
