### ISSUE TITLE
Text v4 error breaks almost everything

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#2056]
**I am currently running**

- SpongeForge version: 1.12.2-2705-8.0.0-BETA-3387:dev
- Java version: 1.8.0_162
- Operating System: Windows 10 x64

**Issue Description**
My plugin has been updated to use text api v4 but when I start my test server I can't even connect and the console is spammed of stacktraces. It looks like most methods related to the text api are broken.

**Logs**
https://pastebin.com/5YYXaGD7

**Comment by ryantheleach** [comment]
@Yeregorix Thanks for the report!

Bleeding Text changes were tested against Nucleus, Some Binary incompatibility changes were observed.

As you know, API 8 isn't released, and breakages between API versions happen.

Moving the text to implementation has been a long-planned change, that was known to have a knock-on effect across almost all plugins.

But I'm looking for a little more info to accompany your log.

1. Have you tried recompiling your plugin against the latest API 8 snapshot? Or was this using the existing jars?

2. If so, are you able to create a [ Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) in order to help see where the issues lie?

**Comment by Yeregorix** [comment]
I've fully recompiled my plugin. In fact I had to modify few things in my code to make it compatible with the new API. Mostly things like: `Text.EMPTY` -> `Text.empty()`, `Text.NEW_LINE` -> `Text.newLine()`.
For the mcv example I will try to do my best if you really need it but I'm not sure it's even needed. If you look at the logs there are stacktraces that are not even related to any plugin: (line 437)
```
java.lang.IllegalArgumentException: Could not find a Supplier for the provided builder class: org.spongepowered.api.text.TextTemplate.Arg.Builder
 	at org.spongepowered.common.registry.SpongeGameRegistry.createBuilder(SpongeGameRegistry.java:354)
 	at org.spongepowered.api.text.TextTemplate.arg(TextTemplate.java:186)
 	at org.spongepowered.api.event.message.MessageEvent$DefaultBodyApplier.<init>(MessageEvent.java:278)
 	at org.spongepowered.api.event.message.MessageEvent$MessageFormatter.<init>(MessageEvent.java:183)
 	at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:601)
 	at net.minecraft.server.network.NetHandlerLoginServer$2.handler$fireAuthEvent$zka000(NetHandlerLoginServer.java:547)
 	at net.minecraft.server.network.NetHandlerLoginServer$2.run(NetHandlerLoginServer.java:198)
```
Here, Sponge failed to fire the auth event due to a text error. I don't think it requires any plugin to reproduce this issue.

Edit: This also explains why I can't connect to the server.

**Comment by gabizou** [comment]
Fixed, thanks for the report!

**Comment by Yeregorix** [comment]
Everything works fine now except that I'm still getting the pretty formatted error message at line 77.
