### ISSUE TITLE
Crash with OpenComputers

### ISSUE THREAD

**Issue by maestrous** [SpongePowered/Sponge#362]
Same crash on server and client.
http://pastebin.com/D1ybvLgd

**Comment by progwml6** [comment]
@maestrous can you give us the full MC log for this?

**Comment by maestrous** [comment]
Yes, please.
http://pastebin.com/3GXbtW7T

**Comment by liach** [comment]
`org.spongepowered.mod.mixin.core.fml.MixinModContainer` should mix in `net.minecraftforge.fml.common.ModContainer` instead of those subclasses. If I recall right Sponge should be treating Forge Mods as plugins.

**Comment by maestrous** [comment]
As i understand this is bug of sponge and not of mod? Good.  I thought this is bug of opencomputers, like no support for sponge or etc. Thanks. I'm waiting for the fix :+1:

**Comment by liach** [comment]
If I recalled right the `MixinModContainer` was supposed to just mix in `ModContainer`. Why to mix in its sub-classes separately?

**Comment by maestrous** [comment]
At that time I did not writed\mixed anything. I just installed the sponge core and opencomputers like mods in order to test compatibility and performance. First time. and only then i want to wrote something under sponge... and i get crash. without opencomputers its ok.
// or this question was not intended for me? :O

**Comment by JBYoshi** [comment]
@liach It can't mix in to `ModContainer` because `ModContainer` is an interface. Mixin only supports classes.

**Comment by simon816** [comment]
For some reason [`MixinModContainer`](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/fml/MixinModContainer.java) didn't mix into `DummyModContainer`, there's only two logged entries for the mixin out of the 3 that it should have
> [20:48:39] [Client thread/DEBUG] [mixin/]: Mixing fml.MixinModContainer from mixins.forge.preinit.json into net.minecraftforge.fml.common.InjectedModContainer
[20:48:39] [Client thread/DEBUG] [mixin/]: Mixing fml.MixinModContainer from mixins.forge.preinit.json into net.minecraftforge.fml.common.FMLModContainer

**Comment by bloodmc** [comment]
Fixed in build 693

**Comment by liach** [comment]
Ok I forgot interfaces cannot have implementations until java 8. My bad.

**Comment by simon816** [comment]
This is not fixed yet, I've opened a ticket on OpenComputers, https://github.com/MightyPirates/OpenComputers/issues/1485

**Comment by simon816** [comment]
OpenComputers has fixed this issue, here's a link to the latest OC dev build http://ci.cil.li/job/OpenComputers-dev-MC1.8/228/
